### ISSUE TITLE
Telemetry injection forces event data content type to JSON

### ISSUE THREAD

**Issue by andersflemmen** [EventStore/EventStoreDB-Client-Java#280] opened 2024-07-10 10:40 UTC
When upgrading the client from version 5.3.0 to 5.4.0, we ran into problems where the system projections were not picking up any events. After some digging, we noticed our Protobuf events were being interpreted as JSON. 

Looks like the problem is caused by this line, which seems to ignore the current format of the event data and just forces it to JSON:
https://github.com/EventStore/EventStoreDB-Client-Java/blob/a7158994d0e37d7d7c4dca5b63ff49a17b01c3bd/db-client-java/src/main/java/com/eventstore/dbclient/ClientTelemetry.java#L34

Should this take the current content type into consideration, or am I missing something?

**Comment by josephcummings** [comment] 2024-07-10 10:53
Hi @andersflemmen 

Thanks for raising this, yes it looks like you are correct.

I will look into this further and prepare a patch for this problem and get back to you shortly.

**Comment by josephcummings** [comment] 2024-07-12 15:10
Hey @andersflemmen

Sorry for the delay, a fix is being prepared now, once merged it will be released as patch `v5.4.1` - I will notify you here once that's available, too.

**Comment by josephcummings** [comment] 2024-07-16 15:42
Hi @andersflemmen 

I can confirm the patch is now available on `v5.4.1`.

Thanks for bringing this to our attention, let me know if you have any further issues going forwards 👍

**Closed as completed by josephcummings** 2024-07-16 15:42 UTC
